### ISSUE TITLE
Animating these changes on Mobile Devices

### ISSUE THREAD

**Issue by De3d** [Unity-Technologies/com.unity.palette-switch#16]
Is this relatively performant on mobile devices for dynamic (during gameplay) updates to many materials within the environment, so as to create dynamically responsive environments?

**Comment by smnwttbr** [comment]
Right now, my opinion is that it is not ready for this kind of usage. The current use-case is material interpolation in a timeline, for use in film production. We haven't tested on any mobile devices.

**Comment by De3d** [comment]
THANK YOU for response. Will stay tuned in the hope this becomes something able to create dynamic environment changes for game happenings. Cheers.

**Comment by sindharta** [comment]
Closing this issue for now. Please let us know if there are other questions.
Plus, we'll try to answer faster next time.
